var LSFA_DATA = {
  "102": {
    "bigImg": "102.jpg",
    "dimensions": "",
    "id": "lsfa102",
    "medImg": "102.png",
    "media": "",
    "name": "Ventian Plaster with Metallic Wash",
    "ordinal": 10200,
    "section": "faux",
    "smallImg": "102.png"
  },
  "103": {
    "bigImg": "103.jpg",
    "dimensions": "",
    "id": "lsfa103",
    "medImg": "103.png",
    "media": "",
    "name": "Dragging and Stencil Finish",
    "ordinal": 10300,
    "section": "faux",
    "smallImg": "103.png"
  },
  "105": {
    "bigImg": "105.jpg",
    "dimensions": "",
    "id": "lsfa105",
    "medImg": "105.png",
    "media": "",
    "name": "Venitian Plaster with Embedded Leaf Pattern",
    "ordinal": 10500,
    "section": "faux",
    "smallImg": "105.png"
  },
  "106": {
    "bigImg": "106.jpg",
    "dimensions": "",
    "id": "lsfa106",
    "medImg": "106.png",
    "media": "",
    "name": "Metallic Color Wash",
    "ordinal": 10600,
    "section": "faux",
    "smallImg": "106.png"
  },
  "107": {
    "bigImg": "107.jpg",
    "dimensions": "",
    "id": "lsfa107",
    "medImg": "107.png",
    "media": "",
    "name": "Aged Damask Pattern",
    "ordinal": 10700,
    "section": "faux",
    "smallImg": "107.png"
  },
  "109": {
    "bigImg": "109.jpg",
    "dimensions": "",
    "id": "lsfa109",
    "medImg": "109.png",
    "media": "",
    "name": "Gesso Trowl and Color Wash",
    "ordinal": 10900,
    "section": "faux",
    "smallImg": "109.png"
  },
  "110": {
    "bigImg": "110.jpg",
    "dimensions": "",
    "id": "lsfa110",
    "medImg": "110.png",
    "media": "",
    "name": "Stencil Over Color Wash",
    "ordinal": 11000,
    "section": "faux",
    "smallImg": "110.png"
  },
  "111": {
    "bigImg": "111.jpg",
    "dimensions": "",
    "id": "lsfa111",
    "medImg": "111.png",
    "media": "",
    "name": "Lime Wash Trowel with Stencil",
    "ordinal": 11100,
    "section": "faux",
    "smallImg": "111.png"
  },
  "112": {
    "bigImg": "112.jpg",
    "dimensions": "",
    "id": "lsfa112",
    "medImg": "112.png",
    "media": "",
    "name": "Metallic Stripe",
    "ordinal": 11200,
    "section": "faux",
    "smallImg": "112.png"
  },
  "113": {
    "bigImg": "113.jpg",
    "dimensions": "",
    "id": "lsfa113",
    "medImg": "113.png",
    "media": "",
    "name": "Ventian Plaster with Metallic Wash and Leaves",
    "ordinal": 11300,
    "section": "faux",
    "smallImg": "113.png"
  },
  "114": {
    "bigImg": "114.jpg",
    "dimensions": "",
    "id": "lsfa114",
    "medImg": "114.png",
    "media": "",
    "name": "Botanical Stencil and Color Wash",
    "ordinal": 11400,
    "section": "faux",
    "smallImg": "114.png"
  },
  "115": {
    "bigImg": "115.jpg",
    "dimensions": "",
    "id": "lsfa115",
    "medImg": "115.png",
    "media": "",
    "name": "Aged Stucco Finish",
    "ordinal": 11500,
    "section": "faux",
    "smallImg": "115.png"
  },
  "117": {
    "bigImg": "117.jpg",
    "dimensions": "",
    "id": "lsfa117",
    "medImg": "117.png",
    "media": "",
    "name": "Leaf Stencil on Mottled Background",
    "ordinal": 11700,
    "section": "faux",
    "smallImg": "117.png"
  },
  "118": {
    "bigImg": "118.jpg",
    "dimensions": "",
    "id": "lsfa118",
    "medImg": "118.png",
    "media": "",
    "name": "Troweled Metallic Finish",
    "ordinal": 11800,
    "section": "faux",
    "smallImg": "118.png"
  },
  "120": {
    "bigImg": "120.jpg",
    "dimensions": "",
    "id": "lsfa120",
    "medImg": "120.png",
    "media": "",
    "name": "Beaded Metallic Finish",
    "ordinal": 12000,
    "section": "faux",
    "smallImg": "120.png"
  },
  "123": {
    "bigImg": "123.jpg",
    "dimensions": "",
    "id": "lsfa123",
    "medImg": "123.png",
    "media": "",
    "name": "Troweled Paint Finish",
    "ordinal": 12300,
    "section": "faux",
    "smallImg": "123.png"
  },
  "124": {
    "bigImg": "124.jpg",
    "dimensions": "",
    "id": "lsfa124",
    "medImg": "124.png",
    "media": "",
    "name": "Metallic Venitian Plaster",
    "ordinal": 12400,
    "section": "faux",
    "smallImg": "124.png"
  },
  "125": {
    "bigImg": "125.jpg",
    "dimensions": "",
    "id": "lsfa125",
    "medImg": "125.png",
    "media": "",
    "name": "Traditional Venitian Plaster",
    "ordinal": 12500,
    "section": "faux",
    "smallImg": "125.png"
  },
  "126": {
    "bigImg": "126.jpg",
    "dimensions": "",
    "id": "lsfa126",
    "medImg": "126.png",
    "media": "",
    "name": "Aged Stone Finish",
    "ordinal": 12600,
    "section": "faux",
    "smallImg": "126.png"
  },
  "128": {
    "bigImg": "128.jpg",
    "dimensions": "18 X 18",
    "id": "lsfa128",
    "medImg": "128.png",
    "media": "oil on canvas",
    "name": "Lillium",
    "ordinal": 12800,
    "section": "home",
    "smallImg": "128.png"
  },
  "129": {
    "bigImg": "129.jpg",
    "dimensions": "21 X 21",
    "id": "lsfa129",
    "medImg": "129.png",
    "media": "oil on canvas",
    "name": "Still Life with Candles and Glass",
    "ordinal": 12900,
    "section": "home",
    "smallImg": "129.png"
  },
  "130": {
    "bigImg": "130.jpg",
    "dimensions": "18 X 23",
    "id": "lsfa130",
    "medImg": "130.png",
    "media": "mix media on paper",
    "name": "Apple Tree",
    "ordinal": 13000,
    "section": "paintings",
    "smallImg": "130.png"
  },
  "131": {
    "bigImg": "131.jpg",
    "dimensions": "29 X 22",
    "id": "lsfa131",
    "medImg": "131.png",
    "media": "watercolor on paper",
    "name": "Peonies with Columbine",
    "ordinal": 13100,
    "section": "paintings",
    "smallImg": "131.png"
  },
  "132": {
    "bigImg": "132.jpg",
    "dimensions": "38 X 28",
    "id": "lsfa132",
    "medImg": "132.png",
    "media": "oil on canvas",
    "name": "Winter",
    "ordinal": 13200,
    "section": "paintings",
    "smallImg": "132.png"
  },
  "133": {
    "bigImg": "133.jpg",
    "dimensions": "24 X 18",
    "id": "lsfa133",
    "medImg": "133.png",
    "media": "conte crayon on paper",
    "name": "Circle of Hands",
    "ordinal": 13300,
    "section": "paintings",
    "smallImg": "133.png"
  },
  "134": {
    "bigImg": "134.jpg",
    "dimensions": "40 X 25",
    "id": "lsfa134",
    "medImg": "134.png",
    "media": "thread mylar and watercolor on paper",
    "name": "Collage",
    "ordinal": 13400,
    "section": "paintings",
    "smallImg": "134.png"
  },
  "135": {
    "bigImg": "135.jpg",
    "dimensions": "45 X 28",
    "id": "lsfa135",
    "medImg": "135.png",
    "media": "oil on canvas",
    "name": "In the Studio",
    "ordinal": 13500,
    "section": "paintings",
    "smallImg": "135.png"
  },
  "136": {
    "bigImg": "136.jpg",
    "dimensions": "40 X 25",
    "id": "lsfa136",
    "medImg": "136.png",
    "media": "myler and watercolor on paper",
    "name": "Design #7",
    "ordinal": 13600,
    "section": "paintings",
    "smallImg": "136.png"
  },
  "137": {
    "bigImg": "137.jpg",
    "dimensions": "26 X 40",
    "id": "lsfa137",
    "medImg": "137.png",
    "media": "watercolor on paper",
    "name": "Iris and Poppies",
    "ordinal": 13700,
    "section": "paintings",
    "smallImg": "137.png"
  },
  "138": {
    "bigImg": "138.jpg",
    "dimensions": "40 X 25",
    "id": "lsfa138",
    "medImg": "138.png",
    "media": "mylar and watercolor on paper",
    "name": "Design #9",
    "ordinal": 13800,
    "section": "paintings",
    "smallImg": "138.png"
  },
  "139": {
    "bigImg": "139.jpg",
    "dimensions": "46 X 28",
    "id": "lsfa139",
    "medImg": "139.png",
    "media": "oil on canvas",
    "name": "Spring Rain",
    "ordinal": 13900,
    "section": "home",
    "smallImg": "139.png"
  },
  "140": {
    "bigImg": "140.jpg",
    "dimensions": "34 X 48",
    "id": "lsfa140",
    "medImg": "140.png",
    "media": "watercolor on paper",
    "name": "Study in Blue",
    "ordinal": 14000,
    "section": "home",
    "smallImg": "140.png"
  },
  "141": {
    "bigImg": "141.jpg",
    "dimensions": "",
    "id": "lsfa141",
    "medImg": "141.png",
    "media": "",
    "name": "Vaulted Ceiling Sky",
    "ordinal": 100,
    "section": "murals",
    "smallImg": "141.png"
  },
  "142": {
    "bigImg": "142.jpg",
    "dimensions": "",
    "id": "lsfa142",
    "medImg": "142.png",
    "media": "",
    "name": "French Countryside",
    "ordinal": 14200,
    "section": "murals",
    "smallImg": "142.png"
  },
  "143": {
    "bigImg": "143.jpg",
    "dimensions": "",
    "id": "lsfa143",
    "medImg": "143.png",
    "media": "",
    "name": "Vaulted Ceiling Sky Detail",
    "ordinal": 100,
    "section": "murals",
    "smallImg": "143.png"
  },
  "144": {
    "bigImg": "144.jpg",
    "dimensions": "",
    "id": "lsfa144",
    "medImg": "144.png",
    "media": "",
    "name": "Comiskey Park Continued",
    "ordinal": 14400,
    "section": "murals",
    "smallImg": "144.png"
  },
  "145": {
    "bigImg": "145.jpg",
    "dimensions": "",
    "id": "lsfa145",
    "medImg": "145.png",
    "media": "",
    "name": "Comiskey Park",
    "ordinal": 14500,
    "section": "murals",
    "smallImg": "145.png"
  },
  "146": {
    "bigImg": "146.jpg",
    "dimensions": "",
    "id": "lsfa146",
    "medImg": "146.png",
    "media": "",
    "name": "Jungle Scene",
    "ordinal": 14600,
    "section": "murals",
    "smallImg": "146.png"
  },
  "147": {
    "bigImg": "147.jpg",
    "dimensions": "",
    "id": "lsfa147",
    "medImg": "147.png",
    "media": "",
    "name": "Garden",
    "ordinal": 14700,
    "section": "murals",
    "smallImg": "147.png"
  },
  "148": {
    "bigImg": "148.jpg",
    "dimensions": "",
    "id": "lsfa148",
    "medImg": "148.png",
    "media": "",
    "name": "Save the Rainforest",
    "ordinal": 14800,
    "section": "murals",
    "smallImg": "148.png"
  },
  "149": {
    "bigImg": "149.jpg",
    "dimensions": "",
    "id": "lsfa149",
    "medImg": "149.png",
    "media": "",
    "name": "Monopoly",
    "ordinal": 14900,
    "section": "murals",
    "smallImg": "149.png"
  },
  "150": {
    "bigImg": "150.jpg",
    "dimensions": "",
    "id": "lsfa150",
    "medImg": "150.png",
    "media": "",
    "name": "Basketball on Vaulted Ceiling",
    "ordinal": 15000,
    "section": "murals",
    "smallImg": "150.png"
  },
  "151": {
    "bigImg": "151.jpg",
    "dimensions": "",
    "id": "lsfa151",
    "medImg": "151.png",
    "media": "",
    "name": "Football",
    "ordinal": 15100,
    "section": "murals",
    "smallImg": "151.png"
  },
  "152": {
    "bigImg": "152.jpg",
    "dimensions": "",
    "id": "lsfa152",
    "medImg": "152.png",
    "media": "",
    "name": "Fresco Painting",
    "ordinal": 15200,
    "section": "murals",
    "smallImg": "152.png"
  },
  "153": {
    "bigImg": "153.jpg",
    "dimensions": "",
    "id": "lsfa153",
    "medImg": "153.png",
    "media": "",
    "name": "Tropical View",
    "ordinal": 15300,
    "section": "murals",
    "smallImg": "153.png"
  },
  "154": {
    "bigImg": "154.jpg",
    "dimensions": "",
    "id": "lsfa154",
    "medImg": "154.png",
    "media": "",
    "name": "Tropical View Detail",
    "ordinal": 15400,
    "section": "murals",
    "smallImg": "154.png"
  },
  "155": {
    "bigImg": "155.jpg",
    "dimensions": "",
    "id": "lsfa155",
    "medImg": "155.png",
    "media": "",
    "name": "The Old Mill",
    "ordinal": 15500,
    "section": "murals",
    "smallImg": "155.png"
  },
  "156": {
    "bigImg": "156.jpg",
    "dimensions": "",
    "id": "lsfa156",
    "medImg": "156.png",
    "media": "",
    "name": "Street Scene",
    "ordinal": 15600,
    "section": "murals",
    "smallImg": "156.png"
  },
  "157": {
    "bigImg": "157.jpg",
    "dimensions": "",
    "id": "lsfa157",
    "medImg": "157.png",
    "media": "",
    "name": "Bench and Flowers",
    "ordinal": 15700,
    "section": "murals",
    "smallImg": "157.png"
  },
  "158": {
    "bigImg": "158.jpg",
    "dimensions": "",
    "id": "lsfa158",
    "medImg": "158.png",
    "media": "",
    "name": "Tree House Detail",
    "ordinal": 15800,
    "section": "murals",
    "smallImg": "158.png"
  },
  "159": {
    "bigImg": "159.jpg",
    "dimensions": "",
    "id": "lsfa159",
    "medImg": "159.png",
    "media": "",
    "name": "Tree House",
    "ordinal": 15900,
    "section": "murals",
    "smallImg": "159.png"
  },
  "160": {
    "bigImg": "160.jpg",
    "dimensions": "",
    "id": "lsfa160",
    "medImg": "160.png",
    "media": "",
    "name": "Painted Nitch and Pillars",
    "ordinal": 16000,
    "section": "murals",
    "smallImg": "160.png"
  },
  "161": {
    "bigImg": "161.jpg",
    "dimensions": "",
    "id": "lsfa161",
    "medImg": "161.png",
    "media": "",
    "name": "Rotunda  Landscape",
    "ordinal": 16100,
    "section": "murals",
    "smallImg": "161.png"
  },
  "162": {
    "bigImg": "162.jpg",
    "dimensions": "",
    "id": "lsfa162",
    "medImg": "162.png",
    "media": "",
    "name": "Tropical Bathroom Detail",
    "ordinal": 16200,
    "section": "murals",
    "smallImg": "162.png"
  },
  "163": {
    "bigImg": "163.jpg",
    "dimensions": "",
    "id": "lsfa163",
    "medImg": "163.png",
    "media": "",
    "name": "Tropical Bathroom",
    "ordinal": 16300,
    "section": "murals",
    "smallImg": "163.png"
  },
  "165": {
    "bigImg": "165.jpg",
    "dimensions": "",
    "id": "lsfa165",
    "medImg": "165.png",
    "media": "",
    "name": "Degas Nude Copy",
    "ordinal": 16500,
    "section": "murals",
    "smallImg": "165.png"
  },
  "166": {
    "bigImg": "166.jpg",
    "dimensions": "",
    "id": "lsfa166",
    "medImg": "166.png",
    "media": "",
    "name": "Davinci Lilly Copy",
    "ordinal": 16600,
    "section": "murals",
    "smallImg": "166.png"
  },
  "IMG_1244": {
    "bigImg": "IMG_1244.jpg",
    "dimensions": "",
    "id": "lsfaIMG_1244",
    "medImg": "IMG_1244.png",
    "media": "",
    "name": "Wrigley Field",
    "ordinal": 100,
    "section": "murals",
    "smallImg": "IMG_1244.png"
  },
  "IMG_1245": {
    "bigImg": "IMG_1245.jpg",
    "dimensions": "",
    "id": "lsfaIMG_1245",
    "medImg": "IMG_1245.png",
    "media": "",
    "name": "Wrigley Field",
    "ordinal": 20000,
    "section": "murals",
    "smallImg": "IMG_1245.png"
  },
  "IMG_1247": {
    "bigImg": "IMG_1247.jpg",
    "dimensions": "",
    "id": "lsfaIMG_1247",
    "medImg": "IMG_1247.png",
    "media": "",
    "name": "Train Mural",
    "ordinal": 20100,
    "section": "murals",
    "smallImg": "IMG_1247.png"
  }
};
